### ISSUE TITLE
node_modules/angular4-social-login/angular4-social-login"' has no exported member 'LoginOpt'.

### ISSUE THREAD

**Issue by batmangotham** [abacritt/angularx-social-login#63]
I am getting this issue when importing LoginOpt 

import {
  SocialLoginModule,
  AuthServiceConfig,
  FacebookLoginProvider,
  LoginOpt
} from "angular4-social-login";

const fbLoginOptions: LoginOpt = {
  scope: "user_birthday,user_photos",
  return_scopes: true,
  enable_profile_selector: true
};

**Comment by jaibatrik** [comment]
Fixed and pushed to npm as well. Kindly check and provide feedback. Did not get time to test.

**Comment by batmangotham** [comment]
Well that issues is fixed But how will i get data of these custom scopes ? I'm not getting it by subscribing to authstate !!

**Comment by jaibatrik** [comment]
Well, this is a problem. The library needs to be enhanced to consider all the custom scopes for Google and Facebook. If you want you can submit a PR that handles the data for the scopes you require. May be create a new issue for that also.

Thanks for reporting anyway!

**Comment by supraja2710** [comment]
The issue still persists for me :( .
My package.json is as follows:

{
  "name": "new-ui",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve   && start gulp",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^4.3.1",
    "@angular/cdk": "^2.0.0-beta.11",
    "@angular/common": "^4.0.0",
    "@angular/compiler": "^4.0.0",
    "@angular/core": "^4.3.1",
    "@angular/forms": "^4.0.0",
    "@angular/http": "^4.0.0",
    "@angular/material": "^2.0.0-beta.11",
    "@angular/platform-browser": "^4.0.0",
    "@angular/platform-browser-dynamic": "^4.0.0",
    "@angular/router": "^4.0.0",
    "@types/jquery": "^3.2.17",
    "@types/moment": "^2.13.0",
    "alasql": "^0.4.4",
    "angular2-highcharts": "^0.5.5",
    "angular2-jwt": "^0.2.3",
    "angular4-social-login": "^1.1.1",
    "angularx-social-login": "^1.1.8",
    "bootstrap": "^3.3.7",
    "chart.js": "^2.7.0",
    "circular-json": "^0.3.3",
    "core-js": "^2.4.1",
    "crypto-js": "^3.1.9-1",
    "d3": "^4.10.0",
    "gulp": "^3.9.1",
    "hammerjs": "^2.0.8",
    "jquery": "^3.2.1",
    "moment": "^2.19.1",
    "moment-timezone": "^0.5.13",
    "ng-drag-drop": "^4.0.0",
    "ng2-charts": "^1.6.0",
    "ng2-dnd": "^4.0.0",
    "ng2-dragula": "^1.5.0",
    "ngx-pagination": "^3.0.3",
    "rxjs": "^5.4.1",
    "typings": "^2.1.1",
    "zone.js": "^0.8.14"
  },
  "devDependencies": {
    "@angular/cli": "1.2.4",
    "@angular/compiler-cli": "^4.0.0",
    "@angular/language-service": "^4.0.0",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/moment": "^2.13.0",
    "@types/moment-timezone": "^0.5.0",
    "@types/node": "^6.0.88",
    "autoprefixer-loader": "^3.2.0",
    "babel-core": "^6.25.0",
    "babel-loader": "^7.1.1",
    "clean-webpack-plugin": "^0.1.16",
    "codelyzer": "~3.0.1",
    "css-loader": "^0.28.4",
    "extract-text-webpack-plugin": "^3.0.0",
    "file-loader": "^0.11.2",
    "html-webpack-plugin": "^2.30.1",
    "image-webpack-loader": "^3.3.1",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "json-loader": "^0.5.7",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "less": "^2.7.2",
    "less-loader": "^4.0.5",
    "ng-annotate": "^1.2.2",
    "ng-annotate-loader": "^0.6.1",
    "ng-cache-loader": "0.0.25",
    "protractor": "~5.1.2",
    "raw-loader": "^0.5.1",
    "style-loader": "^0.18.2",
    "ts-node": "~3.0.4",
    "tslint": "~5.3.2",
    "typescript": "~2.3.3",
    "url-loader": "^0.5.9",
    "webpack": "^3.5.1",
    "webpack-dev-server": "^2.7.0"
  }

**Comment by supraja2710** [comment]
The issue still persists for me :(  Could you please help me out.
Also, could you tell me how to prompt a user everytime they want to login.
My package.json is as follows:
{
  "name": "new-ui",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve    && start gulp",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^4.3.1",
    "@angular/cdk": "^2.0.0-beta.11",
    "@angular/common": "^4.0.0",
    "@angular/compiler": "^4.0.0",
    "@angular/core": "^4.3.1",
    "@angular/forms": "^4.0.0",
    "@angular/http": "^4.0.0",
    "@angular/material": "^2.0.0-beta.11",
    "@angular/platform-browser": "^4.0.0",
    "@angular/platform-browser-dynamic": "^4.0.0",
    "@angular/router": "^4.0.0",
    "@types/jquery": "^3.2.17",
    "@types/moment": "^2.13.0",
    "alasql": "^0.4.4",
    "angular2-highcharts": "^0.5.5",
    "angular2-jwt": "^0.2.3",
    "angular4-social-login": "^1.1.1",
    "angularx-social-login": "^1.1.8",
    "bootstrap": "^3.3.7",
    "chart.js": "^2.7.0",
    "circular-json": "^0.3.3",
    "core-js": "^2.4.1",
    "crypto-js": "^3.1.9-1",
    "d3": "^4.10.0",
    "gulp": "^3.9.1",
    "hammerjs": "^2.0.8",
    "jquery": "^3.2.1",
    "moment": "^2.19.1",
    "moment-timezone": "^0.5.13",
    "ng-drag-drop": "^4.0.0",
    "ng2-charts": "^1.6.0",
    "ng2-dnd": "^4.0.0",
    "ng2-dragula": "^1.5.0",
    "ngx-pagination": "^3.0.3",
    "rxjs": "^5.4.1",
    "typings": "^2.1.1",
    "zone.js": "^0.8.14"
  },
  "devDependencies": {
    "@angular/cli": "1.2.4",
    "@angular/compiler-cli": "^4.0.0",
    "@angular/language-service": "^4.0.0",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/moment": "^2.13.0",
    "@types/moment-timezone": "^0.5.0",
    "@types/node": "^6.0.88",
    "autoprefixer-loader": "^3.2.0",
    "babel-core": "^6.25.0",
    "babel-loader": "^7.1.1",
    "clean-webpack-plugin": "^0.1.16",
    "codelyzer": "~3.0.1",
    "css-loader": "^0.28.4",
    "extract-text-webpack-plugin": "^3.0.0",
    "file-loader": "^0.11.2",
    "html-webpack-plugin": "^2.30.1",
    "image-webpack-loader": "^3.3.1",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "json-loader": "^0.5.7",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "less": "^2.7.2",
    "less-loader": "^4.0.5",
    "ng-annotate": "^1.2.2",
    "ng-annotate-loader": "^0.6.1",
    "ng-cache-loader": "0.0.25",
    "protractor": "~5.1.2",
    "raw-loader": "^0.5.1",
    "style-loader": "^0.18.2",
    "ts-node": "~3.0.4",
    "tslint": "~5.3.2",
    "typescript": "~2.3.3",
    "url-loader": "^0.5.9",
    "webpack": "^3.5.1",
    "webpack-dev-server": "^2.7.0"
  }
}
